export const bcp47MapMin: Map<string, string> = new Map([
    ['ar-sa', 'arabic'],
    ['bn-bd', 'bangla'],
    ['bn-in', 'bangla'],
    ['cs-cz', 'czech'],
    ['da-dk', 'danish'],
    ['de-at', 'german'],
    ['de-ch', 'german'],
    ['de-de', 'german'],
    ['el-gr', 'greek'],
    ['en-au', 'english'],
    ['en-ca', 'english'],
    ['en-gb', 'english'],
    ['en-ie', 'english'],
    ['en-in', 'english'],
    ['en-nz', 'english'],
    ['en-us', 'english'],
    ['en-za', 'english'],
    ['es-ar', 'spanish'],
    ['es-cl', 'spanish'],
    ['es-co', 'spanish'],
    ['es-es', 'spanish'],
    ['es-mx', 'spanish'],
    ['es-us', 'spanish'],
    ['fi-fi', 'finnish'],
    ['fr-be', 'french'],
    ['fr-ca', 'french'],
    ['fr-ch', 'french'],
    ['fr-fr', 'french'],
    ['he-il', 'hebrew'],
    ['hi-in', 'hindi'],
    ['hu-hu', 'hungarian'],
    ['id-id', 'indonesian'],
    ['it-ch', 'italian'],
    ['it-it', 'italian'],
    ['ja-jp', 'japanese'],
    ['ko-kr', 'korean'],
    ['nl-be', 'dutch'],
    ['nl-nl', 'dutch'],
    ['no-no', 'norwegian'],
    ['pl-pl', 'poland'],
    ['pt-br', 'portuguese'],
    ['pt-pt', 'portuguese'],
    ['ro-ro', 'romanian'],
    ['ru-ru', 'russian'],
    ['sk-sk', 'slovak'],
    ['sv-se', 'swedish'],
    ['ta-in', 'tamil'],
    ['ta-lk', 'tamil'],
    ['th-th', 'thai'],
    ['tr-tr', 'turkish'],
    ['zh-cn', 'chinese'],
    ['zh-hk', 'cantonese'],
    ['zh-tw', 'cantonese'],

    ['af-ZA','afrikaans'],
    ['am-ET','amharic'],
    ['az-AZ','azeri'],
    ['bs-BA','bosnian'],
    ['ca-ES','catalan'],
    ['cy-GB','welsh'],
    ['da-DK','danish'],
    ['et-EE','estonian'],
    ['eu-ES','basque'],
    ['fi-FI','finnish'],
    ['ga-IE','irish'],
    ['gl-ES','galician'],
    ['gu-IN','gujarati'],
    ['hy-AM','armenian'],
    ['is-IS','icelandic'],
    ['jv-ID','javanese'],
    ['ka-GE','georgian'],
    ['kk-KZ','kazakh'],
    ['km-KH','cambodia'],
    ['kn-IN','kannada'],
    ['lo-LA','laos'],
    ['lt-LT','lithuanian'],
    ['lv-LV','latvian'],
    ['mk-MK','macedonian'],
    ['mr-IN','marathi'],
    ['mt-MT','maltese'],
    ['nb-NO','norwegian'],
    ['nl-BE','dutch'],
    ['nl-NL','dutch'],
    ['pa-IN','punjabi'],
    ['sk-SK','slovak'],
    ['sl-SI','slovenian'],
    ['so-SO','somali'],
    ['sv-SE','swedish'],
    ['te-IN','telugu'],
    ['uz-UZ','uzbek'],
    ['zu-ZA','zulu'],
    ['su-ID','undanese'],
])