export const bcp47MapMin: Map<string, string> = new Map([
    ['ar-sa', 'arabic'],
    ['bn-bd', 'bangla'],
    ['bn-in', 'bangla'],
    ['cs-cz', 'czech'],
    ['da-dk', 'danish'],
    ['de-at', 'german'],
    ['de-ch', 'german'],
    ['de-de', 'german'],
    ['el-gr', 'greek'],
    ['en-au', 'english'],
    ['en-ca', 'english'],
    ['en-gb', 'english'],
    ['en-ie', 'english'],
    ['en-in', 'english'],
    ['en-nz', 'english'],
    ['en-us', 'english'],
    ['en-za', 'english'],
    ['es-ar', 'spanish'],
    ['es-cl', 'spanish'],
    ['es-co', 'spanish'],
    ['es-es', 'spanish'],
    ['es-mx', 'spanish'],
    ['es-us', 'spanish'],
    ['fi-fi', 'finnish'],
    ['fr-be', 'french'],
    ['fr-ca', 'french'],
    ['fr-ch', 'french'],
    ['fr-fr', 'french'],
    ['he-il', 'hebrew'],
    ['hi-in', 'hindi'],
    ['hu-hu', 'hungarian'],
    ['id-id', 'indonesian'],
    ['it-ch', 'italian'],
    ['it-it', 'italian'],
    ['ja-jp', 'japanese'],
    ['ko-kr', 'korean'],
    ['nl-be', 'dutch'],
    ['nl-nl', 'dutch'],
    ['no-no', 'norwegian'],
    ['pl-pl', 'poland'],
    ['pt-br', 'portuguese'],
    ['pt-pt', 'portuguese'],
    ['ro-ro', 'romanian'],
    ['ru-ru', 'russian'],
    ['sk-sk', 'slovak'],
    ['sv-se', 'swedish'],
    ['ta-in', 'tamil'],
    ['ta-lk', 'tamil'],
    ['th-th', 'thai'],
    ['tr-tr', 'turkish'],
    ['zh-cn', 'chinese'],
    ['zh-hk', 'cantonese'],
    ['zh-tw', 'cantonese'],
    ['af-ZA','Afrikaans'],
    ['am-ET','Amharic'],
    ['az-AZ','Azeri'],
    ['bs-BA','Bosnian'],
    ['ca-ES','Catalan'],
    ['cy-GB','Welsh'],
    ['da-DK','Danish'],
    ['et-EE','Estonian'],
    ['eu-ES','Basque'],
    ['fi-FI','Finnish'],
    ['ga-IE','Irish'],
    ['gl-ES','Galician'],
    ['gu-IN','Gujarati'],
    ['hy-AM','Armenian'],
    ['is-IS','Icelandic'],
    ['jv-ID','Javanese'],
    ['ka-GE','Georgian'],
    ['kk-KZ','Kazakh'],
    ['km-KH','Khmer'],
    ['kn-IN','Kannada'],
    ['lo-LA','Lao'],
    ['lt-LT','Lithuanian'],
    ['lv-LV','Latvian'],
    ['mk-MK','Macedonian'],
    ['mr-IN','Marathi'],
    ['mt-MT','Maltese'],
    ['nb-NO','Norwegian'],
    ['nl-BE','Dutch'],
    ['nl-NL','Dutch'],
    ['pa-IN','Punjabi'],
    ['sk-SK','Slovak'],
    ['sl-SI','Slovenian'],
    ['so-SO','Somali'],
    ['sv-SE','Swedish'],
    ['te-IN','Telugu'],
    ['uz-UZ','Uzbek'],
    ['zu-ZA','Zulu'],
    ['su-ID','Sundanese'],
])